database:
  url: jdbc:mysql://localhost:3306/customer_cascade?useSSL=false&useTimezone=true&serverTimezone=UTC
  username: root
  password: root

spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true